### ISSUE TITLE
 Account error

### ISSUE THREAD

**Issue by MSe-5-14** [gagebenne/pydexcom#10]
Hello,

I'm trying to connect to my girlfriends dexcom account (with her permission and her providing me her credentials). i went onto the dexcom website and tested her credentials. they work. I already use the follow app and receive her glucose info without an issue. 
I try and connect with the following command from the python3 cli
```python3
from pydexcom import Dexcom
Dexcom("GirlFriendsUsername@gmail","Password",ous=True)
```

i then get the following error:
```
Session ID default
Traceback (most recent call last):
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 146, in create_session
    self._validate_session_id()
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 108, in _validate_session_id
    raise SessionError(SESSION_ERROR_SESSION_ID_DEFAULT)
pydexcom.errors.SessionError: Session ID default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 60, in __init__
    self.create_session()
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 148, in create_session
    raise AccountError(ACCOUNT_ERROR_UNKNOWN)
pydexcom.errors.AccountError: Account error
```

when I type the wrong password i get the following error

```
json: {'Code': 'SSO_AuthenticatePasswordInvalid', 'Message': 'Synchronization of SSO account during authenticate call failed.  AccountId=699f0778-3299-442b-a1dc-15746a4a7388 UAM_Error: HttpStatus=\'Unauthorized(401)\' Msg=\'Cannot Authenticate by AccountId=699f0778-3299-442b-a1dc-15746a4a7388\' Content=\'{"id":"f6c40a6f-d326-42bf-932d-958cd135d062","errors":["BadUserNameOrPassword"]}\' Key=\'SSO_AuthenticatePasswordInvalid\'', 'SubCode': '<OnlineException DateThrownLocal="2020-07-09 16:59:54.2272649+00:00" DateThrown="2020-07-09 16:59:54.2272649+00:00" ErrorCode="SSO_AuthenticatePasswordInvalid" Type="15" Category="1" Severity="2" TypeString="SingleSignOn" CategoryString="System" SeverityString="Severe" HostName="" HostIP="" Id="{F2C5A9F8-6143-4564-9F10-39F646B1C7F3}" Message="Synchronization of SSO account during authenticate call failed.  AccountId=699f0778-3299-442b-a1dc-15746a4a7288 UAM_Error: HttpStatus=\'Unauthorized(401)\' Msg=\'Cannot Authenticate by AccountId=699f0778-3299-442b-a1dc-15746a4a7388\' Content=\'{&quot;id&quot;:&quot;f6c40a6f-d326-42bf-932d-958cd135d062&quot;,&quot;errors&quot;:[&quot;BadUserNameOrPassword&quot;]}\' Key=\'SSO_AuthenticatePasswordInvalid\'" FullText="Dexcom.Common.OnlineException: Synchronization of SSO account during authenticate call failed.  AccountId=699f0778-3299-442b-a1dc-15746a4a7388 UAM_Error: HttpStatus=\'Unauthorized(401)\' Msg=\'Cannot Authenticate by AccountId=699f0778-3299-442b-a1dc-15746a4a7388\' Content=\'{&quot;id&quot;:&quot;f6c40a6f-d326-42bf-932d-958cd135d062&quot;,&quot;errors&quot;:[&quot;BadUserNameOrPassword&quot;]}\' Key=\'SSO_AuthenticatePasswordInvalid\'" />', 'TypeName': 'FaultException'}
SSO_AuthenticatePasswordInvalid: Synchronization of SSO account during authenticate call failed.  AccountId=699f0778-3299-442b-a1dc-15746a4a7388 UAM_Error: HttpStatus='Unauthorized(401)' Msg='Cannot Authenticate by AccountId=699f0778-3299-442b-a1dc-15746a4a7388' Content='{"id":"f6c40a6f-d326-42bf-932d-958cd135d062","errors":["BadUserNameOrPassword"]}' Key='SSO_AuthenticatePasswordInvalid'
Traceback (most recent call last):
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 73, in _request
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://shareous1.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 60, in __init__
    self.create_session()
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 142, in create_session
    self.session_id = self._request("post", endpoint1, json=json)
  File "/home/test/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 86, in _request
    raise AccountError(ACCOUNT_ERROR_PASSWORD_INVALID)
pydexcom.errors.AccountError: Password not valid

```
which suggest to me to credentials were correct the first time. what am i missing?

**Comment by gagebenne** [comment]
What country are you located in?

Some people have had problems with connecting when their Dexcom passwords are entirely numeric. If you have connection issues in that case, try changing your password to something with a mix of numbers and letters.

**Comment by MSe-5-14** [comment]
located in Luxembourg (Europe)
Password is alphanumeric. no special characters
i was surprised as well by her username its not a complete email address either. i tried both with her complete email address and the username. Is the @ sign maybe a special character which causes the issue.

**Comment by gagebenne** [comment]
Hm, yeah, it seems like it is okay with your username, because it returns that your password is invalid (it would’ve first returned that your username is invalid if that was the case).

I would try two more things: changing your password, and trying out the US based server.

I just ran tests to make sure that everything is functioning in the same manner, and it seems the case. Let me know if you continue to have problems!

**Comment by MSe-5-14** [comment]
sorry for the delay. 
```
DEBUG:pydexcom:Get session ID
DEBUG:pydexcom:post request to General/AuthenticatePublisherAccount:
DEBUG:pydexcom:url: https://shareous1.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount params:None, json: {'accountName': 'username5@gmail', 'password': 'Password100', 'applicationId': 'd89443d2-327c-4a6f-89e5-496bbb0317db'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): shareous1.dexcom.com:443
DEBUG:urllib3.connectionpool:https://shareous1.dexcom.com:443 "POST /ShareWebServices/Services/General/AuthenticatePublisherAccount HTTP/1.1" 200 38
DEBUG:pydexcom:post request response 200:
DEBUG:pydexcom:json: 699f0778-3299-442b-a1dc-15746a4a7288
DEBUG:pydexcom:post request to General/LoginPublisherAccountByName:
DEBUG:pydexcom:url: https://shareous1.dexcom.com/ShareWebServices/Services/General/LoginPublisherAccountByName params:None, json: {'accountName': 'username5@gmail', 'password': 'Password100', 'applicationId': 'd89443d2-327c-4a6f-89e5-496bbb0317db'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): shareous1.dexcom.com:443
DEBUG:urllib3.connectionpool:https://shareous1.dexcom.com:443 "POST /ShareWebServices/Services/General/LoginPublisherAccountByName HTTP/1.1" 200 38
DEBUG:pydexcom:post request response 200:
DEBUG:pydexcom:json: 00000000-0000-0000-0000-000000000000
ERROR:pydexcom:Session ID default
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 146, in create_session
    self._validate_session_id()
  File "/home/pi/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 108, in _validate_session_id
    raise SessionError(SESSION_ERROR_SESSION_ID_DEFAULT)
pydexcom.errors.SessionError: Session ID default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 60, in __init__
    self.create_session()
  File "/home/pi/.local/lib/python3.7/site-packages/pydexcom/__init__.py", line 148, in create_session
    raise AccountError(ACCOUNT_ERROR_UNKNOWN)
pydexcom.errors.AccountError: Account error
```
I created a new user and then it did work. so the script seems to work. i changed the password but that didnt work...

**Comment by gagebenne** [comment]
Check out issue #12, it may be a similar issue.
