### ISSUE TITLE
RemoteDisconnected exceptions

### ISSUE THREAD

**Issue by bogosj** [gagebenne/pydexcom#52]
I'm encountering the following exception. I don't believe these occurred in v0.2.3. It's not consistent. I'll attempt to address these with my backoff-retry method as well, just thought I'd mention it as it seems new since v0.3.0.

```
Traceback (most recent call last):
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/alert.py", line 53, in <module>
    bg = get_bg_reading()
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/backoff/_sync.py", line [105](https://github.com/bogosj/dexcom-trend-alert/actions/runs/6124811048/job/16625529219#step:4:106), in retry
    ret = target(*args, **kwargs)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/alert.py", line 50, in get_bg_reading
    return dexcom.get_current_glucose_reading()
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/pydexcom/__init__.py", line 299, in get_current_glucose_reading
    glucose_readings = self.get_glucose_readings(minutes=10, max_count=1)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/pydexcom/__init__.py", line 283, in get_glucose_readings
    json_glucose_readings = self._get_glucose_readings(minutes, max_count)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/pydexcom/__init__.py", line 256, in _get_glucose_readings
    return self._post(
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/pydexcom/__init__.py", line [143](https://github.com/bogosj/dexcom-trend-alert/actions/runs/6124811048/job/16625529219#step:4:144), in _post
    response = self.__session.post(
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/work/dexcom-trend-alert/dexcom-trend-alert/env/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by gagebenne** [comment]
I think this has been resolved in the latest version of `pydexcom`. Please let me know if you are still having any troubles.

**Comment by bogosj** [comment]
I'm going to stay pinned to v0.2.3 for now since it does what I need.
