### ISSUE TITLE
500 Server Error - G7

### ISSUE THREAD

**Issue by findthebug** [gagebenne/pydexcom#54]
Try to get the login working but i get all the time the same message. Password not valid. 

- Im located in Switzerland, so i used ous=True
- username is email address, and i changed password to chars-numbers combo.
- using dexcom main account to login
- Using G7 sensor with share active and one follower setup
 

``` python
 
>>> from pydexcom import Dexcom
>>> dexcom = Dexcom("EMAILADDRESS", "PASSWORD", ous=True)
Traceback (most recent call last):
  File "/Users/home/follow/pydexcom/__init__.py", line 151, in _post
    response.raise_for_status()
  File "/Users/home/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://shareous1.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/home/follow/pydexcom/__init__.py", line 129, in __init__
    self._session()
  File "/Users/home/follow/pydexcom/__init__.py", line 242, in _session
    self._account_id = self._get_account_id()
  File "/Users/home/follow/pydexcom/__init__.py", line 215, in _get_account_id
    return self._post(
  File "/Users/home/follow/pydexcom/__init__.py", line 156, in _post
    raise error from http_error
pydexcom.errors.AccountError: Password not valid

```

``` json
{
  "Code": "AccountPasswordInvalid",
  "Message": "Publisher account password failed",
  "SubCode": "<OnlineException DateThrownLocal=\"2023-09-30T08:14:31.554\" DateThrown=\"2023-09-30T08:14:31.554Z\" ErrorCode=\"AccountPasswordInvalid\" Type=\"13\" Category=\"4\" Severity=\"1\" TypeString=\"InvalidPassword\" CategoryString=\"Validation\" SeverityString=\"Minor\" HostName=\"\" HostIP=\"\" Id=\"{8c2c059d-e216-41ba-b2ec-bd591213b717}\" Message=\"Publisher account password failed\" FullText=\"com.dexcom.udp.common.data.exception.OnlineException: Publisher account password failed\" />",
  "TypeName": "FaultException"
}

```

**Comment by findthebug** [comment]
well. I figured it out. The issue is the password length. If you change the password in the dexcom forgot password screen there is the info that your password must be between 8 and 20 chars. The point is, you can add there also passwords with 25 chars, what i did. This 25 char pw will work in the app and web but not via curl. i changed now the pw to 16 chars and it works.
