### ISSUE TITLE
Getting password error accessing pydexcom

### ISSUE THREAD

**Issue by kamblegg** [gagebenne/pydexcom#59]
I'm using same credentials for both Main Dexcom app and follower account. I've 2 profile in Dexcom one is my own email ID and another one with username I created for my daughter selecting which I get CGM data.

Now I'm using follower with same email ID and same password but I'm getting an error while connecting.

Any clue why and how I can resolve that?

Error below 👇

*****************************************

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/pydexcom/__init__.py", line 151, in _post
    response.raise_for_status()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://share2.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 2, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/pydexcom/__init__.py", line 129, in __init__
    self._session()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/pydexcom/__init__.py", line 242, in _session
    self._account_id = self._get_account_id()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/pydexcom/__init__.py", line 215, in _get_account_id
    return self._post(
           ^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/pydexcom/__init__.py", line 156, in _post
    raise error from http_error
pydexcom.errors.AccountError: Password not valid

[Program finished]

**Comment by gagebenne** [comment]
Double check you are using the credentials of the Dexcom user (not follower), as well as the `OUS` flag if user is outside of the US.

**Comment by kamblegg** [comment]
I'm using same details for both follower & Dexcom user. OUS flag I tried but got same error

Do I need any additional access to raised?

**Comment by kamblegg** [comment]
Sorry got closed by mistake

**Comment by gagebenne** [comment]
Be sure the follow shows up in your Dexcom GX application. Be sure to be using an email address, `pydexcom` doesn't support phone credentials.

**Comment by kamblegg** [comment]
On G7 when I logged in with credentials I usually see 2 profile one with my email ID and another which I added for my daughter where we see all CGM data. I'm using email credentials but can see that error 😕

I was trying that on mobile where I installed python.

**Comment by gillesvs** [comment]
Thanks for your answer. When I look at the API V3 documentation, I am not sure Dexcom support this either...
